### ISSUE TITLE
[FBU iOS] Done! :)

### ISSUE THREAD

**Issue by simonpfish** [simonlimon/Flix#1]
My app is complete. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Really nice work! Your app had an amazing attention to UI detail, and we're glad to see you investigate and incorporate features that we didn't discuss. UI customization is vast, but takes effort and very careful configuration to get right.

The point of this homework was to get a chance to implement a TableView (one of the most common views in iOS) and to work with real data over the network (in this case from the Movies Database API).

We have a detailed [Project 2 Feedback Guide](http://courses.codepath.com/snippets/ios_university_fast_track/feedback_guides/project_2_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
